fixed UnixConnector for py3, fixed calling Handler constructor twice,…
PowerDNS/pdns-remotebackend-python pull request #8
Opened 2021-06-14 10:02 UTC by the-vty

Hi,

Thanks for the excellent python module! 
I decided to use it for the RIPE Atlas dyndns project and came up with some fixes/improvements:

- fixed UnixConnector.
- fixed calling Handler constructor twice (mainloop, mainloop3)
- options are passed to the Handler
- context manager for Handler to have better control over freeing resources (db connections/files)
- description and version are overridable.
- implemented test for unix connector
- works on py2 and py3

2021-06-27 15:47 UTC, cmouse commented on src/pdns/remotebackend/__init__.py
> +    def __enter__(self):
what are these?

2021-06-27 15:49 UTC, cmouse requested changes

2021-06-27 15:49 UTC, cmouse commented on src/pdns/remotebackend/unix.py
> +
stray newline?

2021-06-27 15:49 UTC, cmouse commented on tests/test.py
> +        time.sleep(1)
is this really needed?

2021-06-27 15:53 UTC, cmouse commented
Thank you for your merge request, nice to see someone actually using this! =)

2021-06-28 09:22 UTC, the-vty commented on src/pdns/remotebackend/__init__.py
> +    def __enter__(self):
that makes the Handler class to be a context manager. A user is free to override the __exit__() method with resource cleanup code. if not - it behaves completely the same as it was before.

2021-06-28 09:25 UTC, the-vty commented on src/pdns/remotebackend/unix.py
> +
fixed

2021-06-28 09:28 UTC, the-vty commented on tests/test.py
> +        time.sleep(1)
I just added code for testing unix socket interface. I think it useful as it covers more functionality. The sleep() is needed to allow the process to start-up and make a socket. It takes some time.

2021-06-28 09:31 UTC, the-vty commented
Yep. your module is really convenient and clean!

2021-06-28 11:22 UTC, cmouse commented on tests/test.py
> +        time.sleep(1)
i wonder if it would make more sense to wait in a loop with short timeout until the socket file appears?

2021-06-29 07:25 UTC, the-vty commented on tests/test.py
> +        time.sleep(1)
I preferred to keep it simple in this case. I've just committed it with polling.

2021-07-05 09:30 UTC, cmouse commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
i don't see this used anywhere..?

2021-07-05 09:47 UTC, the-vty commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
That's the point. It is useful to pass options in the handler constructor. In my Handler code I use it for passing a path to the data files for example. The self.ttl is used in the record method.

2021-07-05 09:49 UTC, cmouse commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
if the base class does not use it for anything why cannot it be extracted by the child constructor from self.options instead?

2021-07-05 10:01 UTC, the-vty commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
Sorry, I'm bit lost what you mean. The Handler constructor is called from Connector.mainloop(). So that's the only elegant way I see to pass the options from Connector to the Handler. The Handler base class constructor needs to know about the options argument.

2021-07-05 10:04 UTC, cmouse commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
`self.options` is avaiable for anyone who inherits the Handler base class. There should be no reason to extract random values from the options array into the base class.

2021-07-05 10:11 UTC, the-vty commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
Is it really so? Sorry I missed it in the code. Could you please point me to the line number in the original code?

2021-07-05 10:16 UTC, cmouse commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
no, my point is. that if you do `self.options = options`, then `self.options` is available already in your Handler derived class. You do not need to extract random values like `ttl` in the Handler base class. That serves no purpose. =)

2021-07-05 10:32 UTC, the-vty commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
Something like this? See my last commit.

2021-07-05 10:38 UTC, cmouse commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
I think you are still missing the point. You should be extracting all that ttl stuff in your implementation code, not in the base code, since it's not used by the base code at all. You can leave all those `self.options = options` and `h.options = options` things there, **just** remove the `h.ttl` and `self.ttl` bits, and put those in your own implementation code.

2021-07-05 10:46 UTC, the-vty commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
the setting of ttl was is in your code originally. I left it for compatibility. Since i removed the options from the Handler constructor I cannot set ttl anymore in the Handler base class.

2021-07-05 10:51 UTC, cmouse commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
Oh, apologies. It has been a long while since i've last touched this code. I didn't remember it being used. I wasn't seeing that bit in the pull request, so it seemed like you were adding self.ttl yourself.

2021-07-05 10:53 UTC, cmouse commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
OK. After staring hard at the original code, lets move the self.ttl into __init__ of handler, as that is where it belongs. We can remove the ttl assigment from mainloop and mainloop3 and instead call self.handler(options=options), so TTL will be parsed there. Sorry for the silliness.

2021-07-05 11:43 UTC, cmouse commented on src/pdns/remotebackend/__init__.py
> +                h.ttl = self.options['ttl']
this is rendundant now.

2021-07-05 11:43 UTC, cmouse commented on src/pdns/remotebackend/unix.py
> +                h.ttl = options['ttl']
this is redundant now (it's handled in Handler)

2021-07-05 11:51 UTC, the-vty commented on src/pdns/remotebackend/__init__.py
> +            self.ttl = self.options['ttl']
here you go

2021-07-05 11:54 UTC, cmouse commented on src/pdns/remotebackend/unix.py
> +                h.ttl = options['ttl']
last one =)

2021-07-05 11:56 UTC, cmouse approved these changes

2021-07-05 12:00 UTC, cmouse commented
Final detail, can you squash your work so the interim commits go away? I can also use squash & merge button if you prefer.

2021-07-05 12:33 UTC, the-vty commented
squashed :)

2021-07-05 12:35 UTC, merged